backend:
  name: github
  repo: alexmaglez/laura-rrss
  branch: main
  base_url: https://musical-proyects.vercel.app

media_folder: "assets/imagenes"
public_folder: "assets/imagenes"

collections:
  - name: "portfolio"
    label: "Portfolio"
    files:
      - name: "publicaciones"
        label: "Publicaciones"
        file: "data/portfolio.json"
        fields:
          - name: "items"
            label: "Publicaciones"
            widget: "list"
            fields:
              - {label: "Título", name: "titulo", widget: "string"}
              - {label: "Tienda / Cliente", name: "tienda", widget: "string"}
              - {label: "Ciudad", name: "ciudad", widget: "select", options: ["Sotogrande", "Madrid"]}
              - {label: "Fecha", name: "fecha", widget: "date"}
              - {label: "Descripción", name: "descripcion", widget: "text", required: false}
              - {label: "Imagen", name: "imagen", widget: "image"}
