backend:
  name: github
  repo: alexmaglez/laura-rrss
  branch: main
  base_url: https://musical-proyects.vercel.app

media_folder: "assets/imagenes"

collections:
  - name: "publicaciones"
    label: "Publicaciones"
    folder: "data/publicaciones"
    create: true
    fields:
      - {label: "Título", name: "titulo", widget: "string"}
      - {label: "Fecha", name: "fecha", widget: "date"}
      - {label: "Tienda / Cliente", name: "tienda", widget: "string"}
      - {label: "Ciudad", name: "ciudad", widget: "select", options: ["Sotogrande", "Madrid"]}
      - {label: "Descripción", name: "descripcion", widget: "text"}
      - {label: "Imagen o vídeo", name: "media", widget: "image", required: false}
